### PR TITLE
fix(npm): build script wasn't working

### PR DESCRIPTION
**Pull request by juanbrujo**
### Description
bugfix: npm scripts weren't working so I adjusted some directory names and now npm compiles the files and tests ok.

Test: `npm run build`

### CODE REVIEW

**Comment by cjpatoilo** [comment]
Hi @juanbrujo Let me know which version of Node and npm are you using? Could you inform the error that appears to you?

**Comment by juanbrujo** [comment]
```
node -v      
v7.7.2
```
Everything compiling and working OK:

screen shot 2017-05-02 at 10 35 35

BUT output directories are wrong:

screen shot 2017-05-02 at 10 37 15

That's what I fixed in package.json, the routes.

**Comment by cjpatoilo** [comment]
So let me explain to you how does it work. The TEST folder exists to show that the compiler is working without any problems. Note, there is a task to copy the files from the SRC folder to the DIST folder.

This is the SCSS version of Milligram, if you want to use the CSS version you should try this repository https://github.com/milligram/milligram

**Comment by juanbrujo** [comment]
So, why the `dist/` folder un main milligram repo has .css files? 

https://github.com/milligram/milligram/tree/master/dist

**Comment by cjpatoilo** [comment]
Because I have decided to modularize everything, so it facilitates support and maintenance for every need. Each repository is a specific project. 

Here you will find support for each your need: `.css`, `.sass`, `.scss`, `.less`, `.styl`..
https://github.com/milligram

**Pull request closed without merging**
